environment:
  nodejs_version: "11"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - yarn --version
  - yarn install

test_script:
  - yarn test:prod
  - yarn build

build: off
