export const SCOPED_DEPENDENCY_PARENT = Symbol("SCOPED_DEPENDENCY_PARENT");
export const SCOPED_DEPENDENCY = Symbol("SCOPED_DEPENDENCY");
export const SCOPED_DEPENDENCY_CUSTOM_NAME = Symbol("SCOPED_DEPENDENCY_CUSTOM_NAME");
